config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :users
  # root 'home#index'
  root 'users#index'
  # get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :admin
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :correct_admin, only: [:edit, :update, :destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    # we need to tell the system to use the association
    # @user = current_admin.users.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    # we need to tell the system to use the association
    # @user = current_admin.users.build(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_admin
    # id: params[:id] => why not admin_id
    # because devise give it the primary key id
    @user = current_admin.users.find_by(id: params[:id])
    redirect_to users_path, notice: "Not Authorized to edit or delete this user" if @user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :twitter, :admin_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
  <div class="mb-3">
  <%# id: :user_admin_id => for being specific%>
    <%= form.number_field :admin_id, id: :user_admin_id, class: "form-control", placeholder: "Admin Id", value: current_admin.id, type: :hidden %>
  </div>
  <div class="form-group">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/users/_show.html.erb
<div id="<%= dom_id user %>">
    <h1 class="display-4">
      <%= user.first_name %>
      <%= user.last_name %>
    </h1>
    <p class="lead"><%= user.email %></p>
    <hr class="my-4">
    <p><%= user.phone %></p>
    <p><%= user.twitter %></p>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.first_name + " " + user.last_name, user %></td>
  <td><%= user.email %></td>
  <td><%= user.phone %></td>
  <td><%= user.twitter %></td>
  <%# user.admin_id %>
  <td>
    <p>
      <%= link_to "Delete", user, data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete?'}, class: "btn btn-sm btn-outline-danger" %>
    </p>
  </td>
</tr>

app/views/users/edit.html.erb
<br>
<h1>Editing user</h1>
<br>
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user, class: "btn btn-secondary" %>
  <%= link_to "Back to users", users_path, class: "btn btn-dark" %>
</div>

app/views/users/index.html.erb
<% if admin_signed_in? %>
  <h1>Users</h1>

  <div id="users">
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <td>Name:</td>
          <td>Email:</td>
          <td>Phone:</td>
          <td>Twitter:</td>
          <%#<td>AdminId:</td>%>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% if user.admin == current_admin %>
            <%= render user %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to "New user", new_user_path, class: "btn btn-secondary" %>
<% else %>
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
<% end %>

app/views/users/new.html.erb
<br>
<h1>Add new user</h1>
<br>
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: "btn btn-dark" %>
</div>

app/views/users/show.html.erb
<%#= render @user %>
<%= render "show", user: @user %>

<div>
  <% #if @user.admin == current_admin%>
    <%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-primary" %>
    <%= link_to "Delete", @user, data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete?'}, class: "btn btn-danger" %>
  <% #end %>
  <br><br>
  <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
</div>