config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :users
  # root 'home#index'
  root 'users#index'
  # get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    # instance variable - will work everywhere like homepage
    @about_me = "My name is Ei Zar Paing."
    # regular variable = local variable working inside function.
    # about_me = "My name is Ei Zar Paing."
    @answer = 2 + 2
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Rails Guides', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class: "nav-link"%>
        </li>
        <%# <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link"
        </li> %>
        <li class="nav-item">
          <%= link_to 'Add User', new_user_path, class: "nav-link"%>
        </li>
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_admin_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_admin_registration_path, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_admin_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_admin_session_path, class: "nav-link"%>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us ...</h1>
<p>
<%= @about_me %>
</p>
<p>
2 + 2 = <%= @answer %>
</p>
<p>
<% result = 2 * 2 %>
2 * 2 = <%= result %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>